export const placeTypeTranslations: Record<string, string> = {
  accounting: '회계',
  airport: '공항',
  amusement_park: '놀이공원',
  aquarium: '수족관',
  art_gallery: '미술관',
  atm: 'ATM',
  bank: '은행',
  bar: '술집',
  beauty_salon: '미용실',
  bicycle_store: '자전거샵',
  book_store: '서점',
  bowling_alley: '볼링장',
  bus_station: '버스정류장',
  cafe: '카페',
  campground: '캠핑장',
  car_dealer: '자동차대리점',
  car_rental: '차량렌탈',
  car_repair: '자동차수리',
  car_wash: '세차장',
  casino: '카지노',
  cemetery: '묘지',
  church: '교회',
  city_hall: '시청',
  clothing_store: '옷가게',
  convenience_store: '편의점',
  courthouse: '법원',
  dentist: '치과',
  department_store: '백화점',
  doctor: '의사',
  drugstore: '약국',
  electrician: '전기기사',
  electronics_store: '전자제품매장',
  embassy: '대사관',
  fire_station: '소방서',
  florist: '꽃집',
  food: '음식',
  funeral_home: '장례식장',
  furniture_store: '가구점',
  gas_station: '주유소',
  gym: '헬스장',
  hair_care: '헤어케어',
  hardware_store: '철물점',
  hindu_temple: '힌두사원',
  home_goods_store: '가전제품매장',
  hospital: '병원',
  insurance_agency: '보험사',
  jewelry_store: '보석상',
  laundry: '세탁소',
  lawyer: '변호사',
  library: '도서관',
  light_rail_station: '경전철역',
  liquor_store: '주류상점',
  local_government_office: '지방정부사무소',
  locksmith: '자물쇠수리',
  lodging: '숙소',
  meal_delivery: '음식배달',
  meal_takeaway: '음식테이크아웃',
  mosque: '모스크',
  movie_rental: '영화대여',
  movie_theater: '영화관',
  moving_company: '이사업체',
  museum: '박물관',
  night_club: '나이트클럽',
  painter: '화가',
  park: '공원',
  parking: '주차장',
  pet_store: '애완동물가게',
  pharmacy: '약국',
  physiotherapist: '물리치료사',
  place_of_worship: '예배처소',
  plumber: '배관공',
  police: '경찰서',
  post_office: '우체국',
  real_estate_agency: '부동산',
  restaurant: '식당',
  roofing_contractor: '지붕업체',
  rv_park: 'RV공원',
  school: '학교',
  shoe_store: '신발가게',
  shopping_mall: '쇼핑몰',
  spa: '스파',
  stadium: '스타디움',
  storage: '저장소',
  store: '상점',
  subway_station: '지하철역',
  supermarket: '슈퍼마켓',
  synagogue: '유대교회당',
  taxi_stand: '택시승강장',
  train_station: '기차역',
  travel_agency: '여행사',
  university: '대학교',
  veterinary_care: '동물병원',
  zoo: '동물원',
  point_of_interest: '관광명소',
  establishment: '시설',
  intersection: '교차로',
  locality: '지역',
  neighborhood: '동네',
  political: '정치적',
  room: '방',
};

export const GOOGLE_MAP_FIELD = [
  'address_component',
  'adr_address',
  'business_status',
  'formatted_address',
  'geometry',
  'icon',
  'icon_mask_base_uri',
  'icon_background_color',
  'name',
  'permanently_closed',
  'photo',
  'place_id',
  'plus_code',
  'type',
  'url',
  'utc_offset',
  'vicinity',

  'formatted_phone_number',
  'international_phone_number',
  'website',

  'opening_hours',
  'current_opening_hours',
  'secondary_opening_hours',
  'special_days',
  'temporarily_closed',
  'reservable',

  'rating',
  'user_ratings_total',
  'reviews',
  'price_level',

  'serves_beer',
  'serves_wine',
  'serves_breakfast',
  'serves_lunch',
  'serves_dinner',
  'wheelchair_accessible_entrance',
  'delivery',
  'takeout',
] as const;

export const DEFAULT_PLACE_QUERY = [
  'name',
  'formatted_address',
  'icon_background_color',
  'geometry',
  'photo',
  'type',
  'place_id',
] as (typeof GOOGLE_MAP_FIELD)[number][];
